version: '3.8'
services:

  recipe-app-api:
    build:
      context: ../../
      dockerfile: Dockerfile
    image: ${IMAGE}
    environment:
      app.db.url: jdbc:postgresql://recipe-app-db:5432/recipedb?ssl=false
    ports:
      - "8080:8080"

  recipe-app-db:
    image: ${DB_IMAGE}
    ports:
      - "5432:5432"

  recipe-app-web:
    image: ${WEB_IMAGE}
    environment:
      API_URL: "http://localhost:8080"
    ports:
      - "80:80"
